Update test.yaml
installs ROOT with micro mamba

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,8 +3,63 @@ on:  [workflow_dispatch, pull_request, push]
 
 jobs:
   test:
-    runs-on: macos-latest
-    steps:
-     - uses: fastai/workflows/nbdev-ci@master
-       with:
-          version: '3.10'
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -l {0}
+    steps: 
+        - uses: actions/checkout@v3
+        - uses: actions/setup-python@v4
+          with:
+            python-version: '3.10'
+            cache: "pip"
+            cache-dependency-path: settings.ini
+        - name: provision-with-micromamba from environment.yml
+          uses: mamba-org/provision-with-micromamba@main
+        - run: micromamba activate testenv
+        - run: 'which root'
+        - run: python -c 'import ROOT'
+        - name: Test with nbdev
+          env:
+            USE_PRE: ''
+            SKIP_TEST: ''
+            FLAGS: ''
+          run: |
+            set -ux
+            python -m pip install --upgrade pip
+            if [ $USE_PRE ]; then
+              pip install -U git+https://github.com/fastai/fastcore.git
+              pip install -U git+https://github.com/fastai/ghapi.git
+              pip install -U git+https://github.com/fastai/execnb.git
+              pip install -U git+https://github.com/fastai/nbdev.git
+            else
+              pip install -U nbdev
+            fi
+            echo "Doing editable install..."
+            test -f setup.py && pip install -e ".[dev]"
+            echo "Check we are starting with clean git checkout"
+            if [[ `git status --porcelain -uno` ]]; then
+              git diff
+              echo "git status is not clean"
+              false
+            fi
+            echo "Trying to strip out notebooks"
+            nbdev_clean
+            echo "Check that strip out was unnecessary"
+            git diff
+            git status -s # display the status to see which nbs need cleaning up
+            if [[ `git status --porcelain -uno` ]]; then
+              git status -uno
+              echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+              false
+            fi
+            nbdev_export
+            if [[ `git status --porcelain -uno` ]]; then
+              echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+              git status -uno
+              git diff
+              exit 1;
+            fi
+            if [ ! $SKIP_TEST ]; then
+              nbdev_test --flags "$FLAGS"
+            fi
